# Copyright 2021 Piotr Tutak

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Schema Registry Installation
  hosts: schemaregistry
  vars:
    app_dir: "{{ inventory_dir }}/schema-registry"
  vars_files:
    - "{{ inventory_dir }}/common/credentials/passwd.yml"
    - "{{ inventory_dir }}/common/variables/common.yml"
    - "{{ app_dir }}/variables/schema-registry.yml"
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-11-openjdk
  tasks:
    - name: Install Java 11
      dnf:
        name: java-11-openjdk-devel
        state: latest

    - name: Install Maven
      dnf:
        name: maven
        state: latest

    - name: Install Git
      dnf:
        name: git
        state: latest

    - name: Ensure group 'schema-registry' is present
      group:
        name: schema-registry
        state: present

    - name: Create user 'schema-registry'
      user:
        name: schema-registry
        groups: schema-registry
        shell: /sbin/nologin
        append: yes
        create_home: false
        home: /opt/schema-registry

    - name: Download SchemaRegistry
      get_url:
        url: 'https://github.com/confluentinc/schema-registry/archive/v6.0.0.tar.gz'
        dest: /opt

    - name: Unarchive SchemaRegistry
      unarchive:
        remote_src: yes
        src: /opt/schema-registry-6.0.0.tar.gz
        dest: /opt
        owner: schema-registry
        group: schema-registry
        keep_newer: yes

    - name: Create a symlink to SchemaRegistry
      file:
        src: /opt/schema-registry-6.0.0
        dest: /opt/schema-registry
        owner: schema-registry
        group: schema-registry
        state: link

    - name: Compile SchemaRegistry with Maven
      command: mvn install -Dmaven.test.skip=true
      become: yes
      args:
        chdir: /opt/schema-registry

    - name: Recursively change permissions
      file:
        path: /opt/schema-registry
        state: directory
        recurse: yes
        owner: schema-registry
        group: schema-registry


- name: Kafka REST Installation
  hosts: schemaregistry
  vars:
    app_dir: "{{ inventory_dir }}/schema-registry"
  vars_files:
    - "{{ inventory_dir }}/common/credentials/passwd.yml"
    - "{{ inventory_dir }}/common/variables/common.yml"
    - "{{ app_dir }}/variables/kafka-rest.yml"
  tasks:
    - name: Install Java 11
      dnf:
        name: java-11-openjdk-devel
        state: latest

    - name: Ensure group 'kafka-rest' is present
      group:
        name: kafka-rest
        state: present

    - name: Create user 'kafka-rest'
      user:
        name: kafka-rest
        groups: kafka-rest
        shell: /sbin/nologin
        append: yes
        create_home: false
        home: /opt/kafka-rest

    - name: Download 'Kafka REST'
      get_url:
        url: https://github.com/confluentinc/kafka-rest/archive/v6.0.0.tar.gz
        dest: /opt

    - name: Unarchive kafka archive
      unarchive:
        remote_src: yes
        src: /opt/kafka-rest-6.0.0.tar.gz
        dest: /opt
        owner: kafka-rest
        group: kafka-rest
        keep_newer: yes

    - name: Create a symlink to
      file:
        src: /opt/kafka-rest-6.0.0
        dest: "{{ KAFKA_REST_HOME }}"
        owner: kafka-rest
        group: kafka-rest
        state: link

    - name: Compile Rest Utils with Maven
      command: mvn clean package
      become: yes
      args:
        chdir: /opt/kafka-rest

    - name: Recursively change permissions
      file:
        path: /opt/kafka-rest
        state: directory
        recurse: yes
        owner: kafka-rest
        group: kafka-rest
