' Copyright 2021 Piotr Tutak

' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at

'     http://www.apache.org/licenses/LICENSE-2.0

' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml StreamDiagram
   skinparam NodeFontStyle bold
database stream_processing as "Stream Processing Cluster" {
    node flink_master as "flink_master\nnode"
    together {
        node stream1 as "kafka1\nflink1\nnode"
        node stream2 as "kafka2\nflink2\nnode"
        node stream3 as "kafka3\nflink3\nnode"
        node stream4 as "kafka4\nflink4\nnode"
    }
    flink_master --> stream1
    flink_master --> stream2
    flink_master --> stream3
    flink_master --> stream4
}
@enduml
