' Copyright 2021 Piotr Tutak

' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at

'     http://www.apache.org/licenses/LICENSE-2.0

' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml UseCaseDiagram

    actor :Developer: as developer
    actor :Reasoner: as reasoner
    actor :Sensor: as sensor_source
    actor :Edge: as edge_source
    actor :Fog: as fog_source

    package System {
        usecase list_data
        usecase get_data
        usecase put_data
        usecase filter_data
        usecase catalog_data

        get_data --> filter_data : include
        put_data --> catalog_data : include
    }

    developer --> get_data
    reasoner --> get_data
    reasoner --> list_data
    developer --> list_data


    sensor_source --> put_data
    edge_source --> put_data
    fog_source --> put_data

@enduml
